/* eslint-disable @typescript-eslint/no-explicit-any */
// this file is generated by Gemini, so....

declare global {
  interface Window {
    Telegram: Telegram;
  }
}

export interface Telegram {
  WebApp: WebApp;
  // Internal utilities are generally not typed for public use,
  // but we focus on the public WebApp interface.
}

export interface WebApp {
  initData: string;
  initDataUnsafe: WebAppInitData;
  version: string;
  platform: string;
  colorScheme: "light" | "dark";
  themeParams: ThemeParams;
  isExpanded: boolean;
  viewportHeight: number;
  viewportStableHeight: number;
  headerColor: string;
  backgroundColor: string;
  bottomBarColor: string;
  isClosingConfirmationEnabled: boolean;
  isVerticalSwipesEnabled: boolean;
  isFullscreen: boolean;
  isOrientationLocked: boolean;
  safeAreaInset: SafeAreaInset;
  contentSafeAreaInset: SafeAreaInset;
  isActive: boolean;

  BackButton: BackButton;
  MainButton: BottomButton;
  SecondaryButton: BottomButton & {
    position: "left" | "right" | "top" | "bottom";
  };
  SettingsButton: SettingsButton;
  HapticFeedback: HapticFeedback;
  CloudStorage: CloudStorage;
  DeviceStorage: DeviceStorage;
  SecureStorage: SecureStorage;
  BiometricManager: BiometricManager;
  Accelerometer: Accelerometer;
  DeviceOrientation: DeviceOrientation;
  Gyroscope: Gyroscope;
  LocationManager: LocationManager;

  isVersionAtLeast(ver: string): boolean;
  setHeaderColor(color: "bg_color" | "secondary_bg_color" | string): void;
  setBackgroundColor(color: "bg_color" | "secondary_bg_color" | string): void;
  setBottomBarColor(
    color: "bg_color" | "secondary_bg_color" | "bottom_bar_bg_color" | string,
  ): void;
  enableClosingConfirmation(): void;
  disableClosingConfirmation(): void;
  enableVerticalSwipes(): void;
  disableVerticalSwipes(): void;
  lockOrientation(): void;
  unlockOrientation(): void;
  requestFullscreen(): void;
  exitFullscreen(): void;
  addToHomeScreen(): void;
  checkHomeScreenStatus(callback?: (status: string) => void): void;
  onEvent(eventType: EventType, callback: (data?: any) => void): void;
  offEvent(eventType: EventType, callback: (data?: any) => void): void;
  sendData(data: string): void;
  switchInlineQuery(
    query: string,
    choose_chat_types?: Array<"users" | "bots" | "groups" | "channels">,
  ): void;
  openLink(
    url: string,
    options?: { try_instant_view?: boolean; try_browser?: boolean },
  ): void;
  openTelegramLink(url: string, options?: { force_request?: boolean }): void;
  openInvoice(url: string, callback?: (status: string) => void): void;
  showPopup(params: PopupParams, callback?: (button_id: string) => void): void;
  showAlert(message: string, callback?: () => void): void;
  showConfirm(message: string, callback?: (ok: boolean) => void): void;
  showScanQrPopup(
    params: ScanQrPopupParams,
    callback?: (text: string) => boolean | void,
  ): void;
  closeScanQrPopup(): void;
  readTextFromClipboard(callback?: (text: string) => void): void;
  requestWriteAccess(callback?: (allowed: boolean) => void): void;
  requestContact(callback?: (allowed: boolean, response: any) => void): void;
  downloadFile(
    params: { url: string; file_name: string },
    callback?: (accepted: boolean) => void,
  ): void;
  shareToStory(
    media_url: string,
    params?: { text?: string; widget_link?: { url: string; name?: string } },
  ): void;
  shareMessage(msg_id: string, callback?: (success: boolean) => void): void;
  setEmojiStatus(
    custom_emoji_id: string,
    params?: { duration?: number },
    callback?: (success: boolean) => void,
  ): void;
  requestEmojiStatusAccess(callback?: (allowed: boolean) => void): void;
  invokeCustomMethod(
    method: string,
    params: any,
    callback?: (error: any, result: any) => void,
  ): void;
  hideKeyboard(): void;
  ready(): void;
  expand(): void;
  close(options?: { return_back?: boolean }): void;
}

// ---------------- Interfaces ----------------

export interface WebAppInitData {
  query_id?: string;
  user?: WebAppUser;
  receiver?: WebAppUser;
  chat?: WebAppChat;
  chat_type?: "sender" | "private" | "group" | "supergroup" | "channel";
  chat_instance?: string;
  start_param?: string;
  can_send_after?: number;
  auth_date?: number;
  hash?: string;
  [key: string]: any;
}

export interface WebAppUser {
  id: number;
  is_bot?: boolean;
  first_name: string;
  last_name?: string;
  username?: string;
  language_code?: string;
  is_premium?: boolean;
  added_to_attachment_menu?: boolean;
  allows_write_to_pm?: boolean;
  photo_url?: string;
}

export interface WebAppChat {
  id: number;
  type: "group" | "supergroup" | "channel";
  title: string;
  username?: string;
  photo_url?: string;
}

export interface ThemeParams {
  bg_color?: string;
  secondary_bg_color?: string;
  text_color?: string;
  hint_color?: string;
  link_color?: string;
  button_color?: string;
  button_text_color?: string;
  header_bg_color?: string;
  accent_text_color?: string;
  section_bg_color?: string;
  section_header_text_color?: string;
  section_separator_color?: string;
  subtitle_text_color?: string;
  destructive_text_color?: string;
  bottom_bar_bg_color?: string;
  [key: string]: string | undefined;
}

export interface SafeAreaInset {
  top: number;
  bottom: number;
  left: number;
  right: number;
}

export interface BackButton {
  isVisible: boolean;
  onClick(callback: () => void): BackButton;
  offClick(callback: () => void): BackButton;
  show(): BackButton;
  hide(): BackButton;
}

export interface SettingsButton {
  isVisible: boolean;
  onClick(callback: () => void): SettingsButton;
  offClick(callback: () => void): SettingsButton;
  show(): SettingsButton;
  hide(): SettingsButton;
}

export interface BottomButton {
  type: "main" | "secondary";
  text: string;
  color: string;
  textColor: string;
  isVisible: boolean;
  isProgressVisible: boolean;
  isActive: boolean;
  hasShineEffect: boolean;
  setText(text: string): BottomButton;
  onClick(callback: () => void): BottomButton;
  offClick(callback: () => void): BottomButton;
  show(): BottomButton;
  hide(): BottomButton;
  enable(): BottomButton;
  disable(): BottomButton;
  showProgress(leaveActive?: boolean): BottomButton;
  hideProgress(): BottomButton;
  setParams(params: BottomButtonParams): BottomButton;
}

export interface BottomButtonParams {
  text?: string;
  color?: string;
  text_color?: string;
  is_active?: boolean;
  is_visible?: boolean;
  has_shine_effect?: boolean;
  position?: "left" | "right" | "top" | "bottom";
}

export interface HapticFeedback {
  impactOccurred(
    style: "light" | "medium" | "heavy" | "rigid" | "soft",
  ): HapticFeedback;
  notificationOccurred(type: "error" | "success" | "warning"): HapticFeedback;
  selectionChanged(): HapticFeedback;
}

export interface CloudStorage {
  setItem(
    key: string,
    value: string,
    callback?: (error: any, result: boolean) => void,
  ): CloudStorage;
  getItem(
    key: string,
    callback: (error: any, result: string) => void,
  ): CloudStorage;
  getItems(
    keys: string[],
    callback: (error: any, result: { [key: string]: string }) => void,
  ): CloudStorage;
  removeItem(
    key: string,
    callback?: (error: any, result: boolean) => void,
  ): CloudStorage;
  removeItems(
    keys: string[],
    callback?: (error: any, result: boolean) => void,
  ): CloudStorage;
  getKeys(callback: (error: any, result: string[]) => void): CloudStorage;
}

export interface DeviceStorage {
  setItem(
    key: string,
    value: string,
    callback?: (error: any, result: boolean) => void,
  ): DeviceStorage;
  getItem(
    key: string,
    callback: (error: any, result: string) => void,
  ): DeviceStorage;
  removeItem(
    key: string,
    callback?: (error: any, result: boolean) => void,
  ): DeviceStorage;
  clear(callback?: (error: any, result: boolean) => void): DeviceStorage;
}

export interface SecureStorage {
  setItem(
    key: string,
    value: string,
    callback?: (error: any, result: boolean) => void,
  ): SecureStorage;
  getItem(
    key: string,
    callback: (error: any, result: string) => void,
  ): SecureStorage;
  removeItem(
    key: string,
    callback?: (error: any, result: boolean) => void,
  ): SecureStorage;
  clear(callback?: (error: any, result: boolean) => void): SecureStorage;
}

export interface BiometricManager {
  isInited: boolean;
  isBiometricAvailable: boolean;
  biometricType: "finger" | "face" | "unknown";
  isAccessRequested: boolean;
  isAccessGranted: boolean;
  isBiometricTokenSaved: boolean;
  deviceId: string;
  init(callback?: () => void): BiometricManager;
  requestAccess(
    params: { reason?: string },
    callback?: (granted: boolean) => void,
  ): BiometricManager;
  authenticate(
    params: { reason?: string },
    callback?: (success: boolean, token?: string) => void,
  ): BiometricManager;
  updateBiometricToken(
    token: string,
    callback?: (applied: boolean) => void,
  ): BiometricManager;
  openSettings(): BiometricManager;
}

export interface LocationManager {
  isInited: boolean;
  isLocationAvailable: boolean;
  isAccessRequested: boolean;
  isAccessGranted: boolean;
  init(callback?: () => void): LocationManager;
  getLocation(callback: (data: LocationData | null) => void): LocationManager;
  openSettings(): LocationManager;
}

export interface LocationData {
  latitude: number;
  longitude: number;
  altitude: number | null;
  course: number | null;
  speed: number | null;
  horizontal_accuracy: number | null;
  vertical_accuracy: number | null;
  course_accuracy: number | null;
  speed_accuracy: number | null;
}

export interface Accelerometer {
  isStarted: boolean;
  x: number | null;
  y: number | null;
  z: number | null;
  start(
    params: { refresh_rate?: number },
    callback?: (success: boolean) => void,
  ): Accelerometer;
  stop(callback?: (success: boolean) => void): Accelerometer;
}

export interface DeviceOrientation {
  isStarted: boolean;
  absolute: boolean;
  alpha: number | null;
  beta: number | null;
  gamma: number | null;
  start(
    params: { refresh_rate?: number; need_absolute?: boolean },
    callback?: (success: boolean) => void,
  ): DeviceOrientation;
  stop(callback?: (success: boolean) => void): DeviceOrientation;
}

export interface Gyroscope {
  isStarted: boolean;
  x: number | null;
  y: number | null;
  z: number | null;
  start(
    params: { refresh_rate?: number },
    callback?: (success: boolean) => void,
  ): Gyroscope;
  stop(callback?: (success: boolean) => void): Gyroscope;
}

export interface PopupParams {
  title?: string;
  message: string;
  buttons?: PopupButton[];
}

export interface PopupButton {
  id?: string;
  type?: "default" | "ok" | "close" | "cancel" | "destructive";
  text?: string;
}

export interface ScanQrPopupParams {
  text?: string;
}

export type EventType =
  | "themeChanged"
  | "viewportChanged"
  | "mainButtonClicked"
  | "secondaryButtonClicked"
  | "backButtonClicked"
  | "settingsButtonClicked"
  | "invoiceClosed"
  | "popupClosed"
  | "qrTextReceived"
  | "scanQrPopupClosed"
  | "clipboardTextReceived"
  | "writeAccessRequested"
  | "contactRequested"
  | "biometricManagerUpdated"
  | "biometricAuthRequested"
  | "biometricTokenUpdated"
  | "locationManagerUpdated"
  | "locationRequested"
  | "accelerometerStarted"
  | "accelerometerStopped"
  | "accelerometerChanged"
  | "accelerometerFailed"
  | "deviceOrientationStarted"
  | "deviceOrientationStopped"
  | "deviceOrientationChanged"
  | "deviceOrientationFailed"
  | "gyroscopeStarted"
  | "gyroscopeStopped"
  | "gyroscopeChanged"
  | "gyroscopeFailed"
  | "fullscreenChanged"
  | "fullscreenFailed"
  | "homeScreenAdded"
  | "homeScreenChecked"
  | "shareMessageSent"
  | "shareMessageFailed"
  | "emojiStatusSet"
  | "emojiStatusFailed"
  | "emojiStatusAccessRequested"
  | "fileDownloadRequested"
  | "safeAreaChanged"
  | "contentSafeAreaChanged"
  | "activated"
  | "deactivated";
